import React from "react";
import { Poppins } from 'next/font/google'
import "@/styles/globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><main className={`${poppins.className} relative`}>{children}</main></body>
    </html>
  )
}